### ISSUE TITLE
Load data from KS without the GUI

### ISSUE THREAD

**Issue by GRVite** [pynapple-org/pynapple#130]
Hello! Is there a method to create the .nwb file without utilizing the GUI? The GUI is useful, but not very efficient for loading multiple sessions. I am unsure if there is an existing solution for this issue. 
If it is necessary to implement a new approach, what would be the most effective way to accomplish this? How to take advantage of the existing code?

**Comment by vigji** [comment]
I agree that this would be a very convenient feature!
Maybe the information to use to fill in the interface metadata could be parsed from a suitably formatted `.json` file if it can be found in the data folder?

**Comment by gviejo** [comment]
Referencing  #134 #133 #132 #131 #98 #120 #110 #97 #95

Hi guys (and welcome back @vigji )

This is a general responses regarding all the issues with the pynapple.IO. I would like to detail here the plan of what is gonna happen in the coming weeks. You can see the general idea in the image below :
![New_pynapple_io](https://github.com/pynapple-org/pynapple/assets/4353798/6b59f570-1af4-43c7-bb0b-4f83bc8ba4c5)

1. First of all, you guys should check [neuroconv](https://neuroconv.readthedocs.io/en/main/index.html). It's basically the same idea as the current pynapple.IO but it supports many more formats. @vigji I would divert the effort for loading phy data to this package which is more advanced than the pynapple IO. It will also favors uniformity across NWB. I can still review and accept your recent PRs.
2. Consequently, the current pynapple.IO has become quite irrelevant now especially if the people at catalystneuro are actively maintaining neuroconv. The idea is to deprecate the current pynapple.IO and move the code to another standalone package [nwbmatic](https://github.com/pynapple-org/nwbmatic). People who want to use the GUI can still install it and use it for creating NWB file. It will also reduce dependencies for pynapple (e.g. tiff, zarr) so better for the long term stability. Ideally, nwbmatic should rely a lot on neuroconv to ensure uniformity here as well.
3. The new pynapple IO will then contain one class to interface with NWB in the most user friendly way (tbd). There is a lot to be done here but the transition from a NWB file to a pynapple object should be as smooth as possible.
4. The other class will provide a way to interface with a dataset following [bids](https://bids-standard.github.io/bids-starter-kit/index.html) specifications. This new Container class will facilitate postprocessing of the data which is sometimes an issue for NWB since you can't overwrite an existing NWB dataset. Currently, pynapple offers saving functions using the npz format (see [here](https://pynapple-org.github.io/pynapple/core.time_series/#pynapple.core.time_series.Tsd.save) for an example for Tsd.save). The Container class will facilitate loading and writing npz or nwb. It will also facilitate walking or looping though an existing datasets (assuming the dataset is structured with folders which is not a too big assumption). You can check the examples below to get an idea of the new pynapple IO. Happy to take feedbacks.

The first step is to load a project : 
![image](https://github.com/pynapple-org/pynapple/assets/4353798/2c41406d-c464-40fe-b8c7-1e4755fc1f45)
The new pynapple IO will search for any NWB file or NPZ files that can be loaded with pynapple (there is a key "t" indicating time index).

It is then easy to navigate a dataset:
![image](https://github.com/pynapple-org/pynapple/assets/4353798/36c5f8cd-cecb-4d29-a5af-8fa4e4e989e6)

Pynapple objects can be lazy loaded:
![image](https://github.com/pynapple-org/pynapple/assets/4353798/464828bf-2c41-4561-ba16-0822e377be7a)

You can add more postprocessing data : 
![image](https://github.com/pynapple-org/pynapple/assets/4353798/5e66d940-e6d0-42c3-ba76-8ab067b3de72)
Following BIDS specs, any npz file will have json sidecar for storing metadata when saved throught the Container class of pynapple.

**Comment by vigji** [comment]
> Hi guys (and welcome back @vigji )

Hi @gviejo, that you very much for the clear and extensive roadmap you detailed here! As per your points:

> 1. First of all, you guys should check [neuroconv](https://neuroconv.readthedocs.io/en/main/index.html). It's basically the same idea as the current pynapple.IO but it supports many more formats. @vigji I would divert the effort for loading phy data to this package which is more advanced than the pynapple IO. It will also favors uniformity across NWB. I can still review and accept your recent PRs.

This makes perfect sense! (If it not a problem, it would still be good if you can merge the PR so I don't have to switch the dependency right now that I temporarily figured the loading with pyneapple) but yes, I will definitively refer to the other library for further development!

> 2. Consequently, the current pynapple.IO has become quite irrelevant now especially if the people at catalystneuro are actively maintaining neuroconv. The idea is to deprecate the current pynapple.IO and move the code to another standalone package [nwbmatic](https://github.com/pynapple-org/nwbmatic). People who want to use the GUI can still install it and use it for creating NWB file. It will also reduce dependencies for pynapple (e.g. tiff, zarr) so better for the long term stability. Ideally, nwbmatic should rely a lot on neuroconv to ensure uniformity here as well.

Very reasonable, I'll keep the `nwbmatic` repo in mind over the next weeks then!

> 3. The new pynapple IO will then contain one class to interface with NWB in the most user friendly way (tbd). There is a lot to be done here but the transition from a NWB file to a pynapple object should be as smooth as possible.
> 4. The other class will provide a way to interface with a dataset following [bids](https://bids-standard.github.io/bids-starter-kit/index.html) specifications. This new Container class will facilitate postprocessing of the data which is sometimes an issue for NWB since you can't overwrite an existing NWB dataset. Currently, pynapple offers saving functions using the npz format (see [here](https://pynapple-org.github.io/pynapple/core.time_series/#pynapple.core.time_series.Tsd.save) for an example for Tsd.save). The Container class will facilitate loading and writing npz or nwb. It will also facilitate walking or looping though an existing datasets (assuming the dataset is structured with folders which is not a too big assumption). You can check the examples below to get an idea of the new pynapple IO. Happy to take feedbacks.

Great fan of bids, I think this is an excellent choice! Something like this interface looks very reasonable to me, I also wanted to start organising my analyses in something like this structure. I'll watch this closely! Is it happening in the `new-io` branch?

**Comment by gviejo** [comment]
@vigji I am not sure I understand it. Could you give more details about this feature or some pseudo code maybe?

**Comment by vigji** [comment]
Maybe it is beyond the scope and the intentions of this, but I'll draft it anyway:

Imagine you have some data from which you intend to compute derivatives. For the sake of an example, imagine there is a raw movie from which we extract positions of the animal with a function that uses some parameters; or, that we create a table of neurons computed selectivity. What those example applications have in common is:
 - derivative data that are produced by some computation;
 - the computation is heavy we do not want to run it at every script / figure generation / notebook etc
 - the computation is parameter-dependent: at some point one might want to tinker and change those parameters.

Imagine that the video analysis is performed in a function (could also be a method of a suitable class, but to get the idea):
 ```python
def get_animal_position(Container, param1=0, param2="b"):
    ...
   return position_array
```

I am thinking about something like a decorator (or a decorator factory) that does something like
 ```python
@bid_cache(cache_folder="analysis")
def get_animal_position(Container, param1=0, param2="b"):
    ...
```

Which compute the result, saves it by default in a desired folder with a name that could be specified or the function name, so that first time I call the function it runs, second time it load the results, or it also runs again if I change the parameters.

**Comment by gviejo** [comment]
Ok I see. It's a nice idea in fact. If well implemented and well tested, that could be nice feature of the new pynapple IO.

**Comment by dlevenstein** [comment]
+1 this container thing is a cool idea

**Comment by vigji** [comment]
I have a question on your thoughts re: the BIDS implementation. I am asking here as that's where I saw it discussed before, lmk if this should go somewhere else.

As much as I like the BIDS format, it feels to me like it would produce some duplication with what an `nwb` file aims to be, no? In terms of where metadata should go, etc. How do you decide what data to structure in the subfolders and what data to the nwb file? How are you doing it atm? 

I am asking as I am trying to commit to a unique way of storing my dataset; as I go through the `NeuroConv` package I would be incentivised to convert as much as possible of my source data into nwb. Would you then keep in BIDS just the derivatives, as it can be annoying to rewrite them constantly to nwb? Should the animal metadata go into the BIDS json? Wouldn't that be a duplication of what I've put in NWB? Are you just aiming at a super light "BIDS-like" structure, that does not do any prescription in terms of where to keep info, and ignore eg a json sidecar for the nwb?

Is there a broader discussion of nwb and BIDS as per September 2023? Tagging @bendichter as I have seen him discussing the issue in the past. I saw that DANDI is currently committing to either NWB for animal physiology and BIDS for imaging data. Wouldn't it feel a bit of a double commitment keeping both kind of data structures together in `pynapple`?

**Comment by bendichter** [comment]
@vigji Let's move conversations like this to the [NWB helpdesk](https://github.com/NeurodataWithoutBorders/helpdesk/discussions).

In short, yes. We have been working with the BIDS team to see if we can create a mutually compatible format, but there are some tricky spots. Combining NWB and BIDS has two major limitations. 1. redundancy of metadata and 2. BIDS likes to separate recordings streams into different files and even different directories and NWB likes to put different recording streams into the same file. Any attempt to combine the two will need to navigate these. The [DANDI Archive](dandiarchive.org) currently uses a "BIDS-like" format that makes compromises favoring NWB. [BIDS-animal-ephys](https://neuroinformatics.incf.org/node/242) is another attempt to marry the two standards, but favors more the BIDS side.

**Comment by gviejo** [comment]
Hi replying here for pynapple. My view was close to was you described as super light "BIDS-like" structure. You can navigate a structured dataset easily and every files you save can have a json sidecar. Those files typically are output of processes that you don't want to repeat. And then every session folder contains the NWB file that was created after the preprocessing. 
I can keep discussing this on the NWB helpdesk too.

**Comment by gviejo** [comment]
Most of this has been implemented so closing the issue.
