### ISSUE TITLE
Units data wrongly read from NWB files

### ISSUE THREAD

**Issue by MKVarun** [pynapple-org/pynapple#164]
I'm trying to read data stored in nwb files. Although the data in KSLabel data is stored correctly in the nwb file, the units TsGroup has the wrong data under the KSLabel column.

![units_error](https://github.com/pynapple-org/pynapple/assets/32513756/e7540270-ea66-4a86-a3ff-89cae59e6321)

**Comment by gviejo** [comment]
Is it a NWB File on Dandi? Can you share the link?

**Comment by MKVarun** [comment]
The NWB file is not on Dandi yet. I created it by converting my ephys data using neuroconv.

**Comment by CodyCBakerPhD** [comment]
Can you print a screenshot of `read_nwbfile.units.to_dataframe()` for a full comparison to the table structure?

**Comment by CodyCBakerPhD** [comment]
Thanks - I suspect then, it it simply a slight misalignment of the column labels and their values on pynapple's parser

**Comment by gviejo** [comment]
Hi guys. I found the issue when looking at the `pynwb.misc.Units` object. It looks like this :
```python
units pynwb.misc.Units at 0x140163422613904
Fields:
  colnames: ['spike_times' 'unit_name' 'KSLabel' 'Amplitude' 'KSLabel_repeat'
 'original_cluster_id' 'ContamPct']
  columns: (
    spike_times_index <class 'hdmf.common.table.VectorIndex'>,
    spike_times <class 'hdmf.common.table.VectorData'>,
    unit_name <class 'hdmf.common.table.VectorData'>,
    KSLabel <class 'hdmf.common.table.VectorData'>,
    Amplitude <class 'hdmf.common.table.VectorData'>,
    KSLabel_repeat <class 'hdmf.common.table.VectorData'>,
    original_cluster_id <class 'hdmf.common.table.VectorData'>,
    ContamPct <class 'hdmf.common.table.VectorData'>
  )
  description: Autogenerated by neuroconv.
  id: id <class 'hdmf.common.table.ElementIdentifiers'>
  waveform_unit: volts
```
`obj.colnames` has 7 elements : `('spike_times', 'unit_name', 'KSLabel', 'Amplitude', 'KSLabel_repeat', 'original_cluster_id', 'ContamPct')`

and `obj,columns` has 8 elements: `(obj.spike_times_index, obj.spike_times, obj.unit_name, ...)`

Pynapple was doing : 
```python
    for colname, col in zip(obj.colnames, obj.columns):
        if colname not in ["spike_times_index", "spike_times"]:

```
causing the misalignment. 

Is having both `obj.spike_times_index` and `obj.spike_times` something always expected @CodyCBakerPhD ?
Should I replace the parsing of the metadata with a call to `obj.to_dataframe()`?

**Comment by CodyCBakerPhD** [comment]
> Is having both obj.spike_times_index and obj.spike_times something always expected @CodyCBakerPhD ?

Yep, `spike_times` is both a required column of the `Units` table, and an indexed column

Every indexed column has a sister `_index` column describing _how_ to index its values

Normally this stuff is hidden by the PyNWB API when you call methods like `units.get_unit_spike_times`, but for other more arbitrary custom columns (which could be indexed or not) I think you do have to go deeper into the underlying `columns` and their `data`

In general, I would never include the values of a `_index` column in a table view of any `DynamicTable` entity; instead, I would use that `_index` column to map the array-valued data (in this case, spike times for each unit) to each row of the table under the hood

That's what `.to_dataframe()` does, and returns of course as a `pandas.DataFrame`



> Should I replace the parsing of the metadata with a call to obj.to_dataframe()?

Heh. Well, what I said above may seem to imply that is what I suggest - _however_ - there are many cases where the call to `.to_dataframe()` is incredibly inefficient and can cause the users machine to freeze up either due to excessive CPU operations (for which there no progress bar) or even overfilling RAM (on devices with lower RAM availability).

This is because, while the `pandas.DataFrame` is very intuitive to work with, it does not leverage the data engineering offered by the NWB backend - it loads the table, in its entirety, into memory.

In this particular users case, and for most standard kilosort/phy output from NeuroConv, that would be fine. But if you want a case of a `Units` table you would not want to do this to, check out one of the Brain Wide Map processed-only files from DANDI. Reason being they have a ton of derived quality metrics for each spike and unit, and a lot of those are therefore arrays just as long as the spike times. And in general, any `Units` table that has `waveforms` would be in the category of 'too big to load efficiently into a `pandas.DataFrame`'

So, if you want `pynapple`'s NWB parsing to be super efficient, I would strongly recommend interacting with the underlying data objects directly instead of `pandas`. Though that is more work and less convenient for you, the developer, I'd be happy to help point you in the right directions or review any PRs you might want feedback on

In particular,

> for colname, col in zip(obj.colnames, obj.columns):

I am shocked that `zip` doesn't complain about mismatched lengths, but an (in)sanity check in Python 3.11

```python
a = zip(range(3), range(4))
b = zip(list(range(3)), list(range(4)))  # this one even knows the `len()` of each item...
```

verifies no error...

Anyway, what I would do there is instead of doing a joint iteration, just do a single iteration over the names and fetching the column from the table using that name

```python
for column_name in obj.colnames:
    column = obj[column_name]
```

**Comment by gviejo** [comment]
Ok thanks for the explanation. The last suggestion is probably the best solution. I will post here the PR when it's ready.

**Comment by gviejo** [comment]
OK I just bumped a version as it was a sensitive issue. I tested it on the same nwb file and it works now making sure it's the latest version installed (v0.3.6). Closing the issue,
